import type { Config } from "tailwindcss";

export default {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface": "#f4faff",
        "surface-dim": "#d2dbe1",
        "surface-bright": "#f4faff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ecf5fb",
        "surface-container": "#e6eff5",
        "surface-container-high": "#e0e9ef",
        "surface-container-highest": "#dbe4ea",
        "on-surface": "#141d21",
        "on-surface-variant": "#3e4851",
        "inverse-surface": "#293236",
        "inverse-on-surface": "#e9f2f8",
        "outline": "#6f7882",
        "outline-variant": "#bec8d2",
        "surface-tint": "#006494",
        "primary": "#006494",
        "on-primary": "#ffffff",
        "primary-container": "#00a0e9",
        "on-primary-container": "#00334e",
        "inverse-primary": "#8ecdff",
        "secondary": "#705d00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fcd400",
        "on-secondary-container": "#6e5c00",
        "tertiary": "#c00014",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ff6459",
        "on-tertiary-container": "#670006",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#cae6ff",
        "primary-fixed-dim": "#8ecdff",
        "on-primary-fixed": "#001e30",
        "on-primary-fixed-variant": "#004b70",
        "secondary-fixed": "#ffe16d",
        "secondary-fixed-dim": "#e9c400",
        "on-secondary-fixed": "#221b00",
        "on-secondary-fixed-variant": "#544600",
        "tertiary-fixed": "#ffdad6",
        "tertiary-fixed-dim": "#ffb4ab",
        "on-tertiary-fixed": "#410002",
        "on-tertiary-fixed-variant": "#93000d",
        "background": "#f4faff",
        "on-background": "#141d21",
        "surface-variant": "#dbe4ea",
        
        // Aliases for the user's custom classes
        "doraemon-darkBlue": "#00334e", // on-primary-container
        "doraemon-blue": "#006494",     // primary
        "doraemon-yellow": "#fcd400",   // secondary-container
        "doraemon-red": "#c00014",      // tertiary
        "doraemon-bg": "#f4faff",       // background
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "label-md": ["Geist", "monospace"],
        "code-sm": ["Geist", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "code-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "container-max": "1200px",
        "gutter": "24px",
      }
    },
  },
  plugins: [],
} satisfies Config;
